### ISSUE TITLE
Card Display mockup

### ISSUE THREAD

**Issue by SirLich** [UMM-CSci-3601-F17/interation-1-raymond_shayler#2]
Make a card display mockup, that shows some hardcoded card values.
Should be mobile friendly.

**Comment by UnwarySage** [comment]
Initial implementation done.
see the above commit.
Needs tests.

**Comment by UnwarySage** [comment]
Also, can't see them in mongoExplorer?
Our unittests on CardController should catch us not adding cards, IIRC, but we should check.
